version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitaca-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - WORKERS=4
    ports:
      - "3000:3000"
    networks:
      - bitaca-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.abitaca.project=bitaca-cinema"
      - "com.abitaca.service=api"


networks:
  bitaca-network:
    driver: bridge
    name: bitaca-network

volumes:
  logs:
    name: bitaca-logs